sudo: false
language: ruby
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
env:
  - TEST_SYMLINK="no"
  - TEST_SYMLINK="yes"
matrix:
  allow_failures:
    - rvm: ruby-head
before_script:
  - bundle exec rake before_script
after_script:
  - bundle exec rake after_script
